### ISSUE TITLE
Package is not compatible with monoandroid13.

### ISSUE THREAD

**Issue by creaworlds** [Softeq/Zendesk-xamarin-android#5]
I've received the following error working in Visual Studio for Mac (17.6.6).
Package Softeq.ZendeskSupport.Droid 5.1.0.1 is not compatible with monoandroid13.0 (MonoAndroid,Version=v13.0). Package Softeq.ZendeskSupport.Droid 5.1.0.1 supports: net6.0-android31.0 (.NETCoreApp,Version=v6.0)

**Comment by wcoder** [comment]
@creaworlds

Xamarin projects have different target frameworks: https://learn.microsoft.com/en-us/dotnet/standard/frameworks

This errors means that your project has old target framework declaration `monoandroid13.0`

`Softeq.ZendeskSupport.Droid` NuGet package has different versions for this:
<table>
<tr>
 <td>5.1.0.1
 <td>net6.0-android31.0
 <td>latest
<tr>
 <td>5.1.0
 <td>monoandroid12.0
</table>

You should use the older version of this package **v5.1.0** for your project.

Please pay attention to the "Frameworks" tab on NuGet:
https://www.nuget.org/packages/Softeq.ZendeskSupport.Droid/5.1.0#supportedframeworks-body-tab

**Comment by creaworlds** [comment]
Thanks for your help. 

I did, but it doesn't work. "Zendesk.Chat" does not exist in 5.1.0.

Am I missing something?

**Comment by wcoder** [comment]
Yes, was mentioned `ZendeskSupport.Droid` -> 5.1.0

Zendesk.Chat SDK for Xamarin has different versions depending on platforms:
- Android: https://www.nuget.org/packages/Softeq.ZendeskChat.Droid
- iOS: https://www.nuget.org/packages/Softeq.ZendeskChatSDK.iOS
