### ISSUE TITLE
It`s Possible open messaging chat using the Wrapper?

### ISSUE THREAD

**Issue by pmartinsesa** [Softeq/Zendesk-xamarin-android#9]
Hello everyone,  

I'm trying to implement the Zendesk Web Widget Messaging chat in my app using Xamarin. However, when following the official Zendesk documentation that uses `Zendesk.Messaging` to achieve this:  
[Zendesk Messaging SDK Documentation](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/getting_started/),  

I couldn't find a way to properly implement it through the wrapper. The methods mentioned in the documentation don't seem to exist in the version I'm using.  

Softeq.ZendeskChat.Droid-3.3.6  
Softeq.ZendeskChatProviders.Droid-3.3.6  
Softeq.ZendeskChatSocketClient.Droid-6.1.3  
Softeq.ZendeskChatVisitorClient.Droid-8.3.3  
Softeq.ZendeskCommonUI.Droid-4.0.1  
Softeq.ZendeskCore.Droid-4.0.2  
Softeq.ZendeskGuide.Droid-1.0.1  
Softeq.ZendeskGuideProviders.Droid-1.0.1  
Softeq.ZendeskMessaging.Droid-5.2.5  
Softeq.ZendeskMessagingAPI.Droid-5.0.1  
Softeq.ZendeskSDKConfigurations.Droid-2.0.0  
Softeq.ZendeskSupport.Droid-5.1.0  
Softeq.ZendeskSupportProviders.Droid-5.0.2  

Could you please let me know if there's another way to make this implementation? Alternatively, has this issue been resolved in the most recent versions of the SDK? If possible, I would really appreciate a small example of how to do it.  

Thank you so much for your attention and help!  

Best regards.

**Comment by yauhenipakala** [comment]
Thank you for reaching out. This repository focuses on the Classic Zendesk SDK: [Classic Zendesk SDK Documentation](https://developer.zendesk.com/documentation/classic-web-widget-sdks/).

We would be deeply grateful for your contribution to the community if you could create a wrapper for new Zendesk SDKs and send PR.

**Comment by pmartinsesa** [comment]
No problem. 

Thank you once again for your time and attention! I'll think about this new wrapper.

**Comment by pmartinsesa** [comment]
Hi everyone,

I’ve created a wrapper for Zendesk Messaging 2.14.0 on Android, and I’m planning to develop one for iOS as well. Just wanted to share it with you:
[ZendeskBindingLibraryAndroid](https://github.com/pmartinsesa/ZendeskBindingLibraryAndroid).

I’d like to thank you all — your Android project has been very helpful, and I’m sure the iOS project will be just as valuable. :)

Cheers!
